ekf_se_odom:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /wheel_odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true]
    odom0_differential: false
    odom0_relative:     false

    imu0: /ferrari/imu/data # /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true]
    imu0_differential: false
    imu0_relative:     false
    imu0_remove_gravitational_acceleration: true
