ekf_se_odom_op:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom_op
    base_link_frame: base_link_op
    world_frame: odom_op

    odom0: /wheel_odom_op
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true]
    odom0_differential: false
    odom0_relative:     false

    imu0: /ferrari_op/imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true]
    imu0_differential: false
    imu0_relative:     false
    imu0_remove_gravitational_acceleration: true
